services:
  postgres:
    ports:
      - ${POSTGRES_PORT}:5432
  api:
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    ports:
      - ${API_PORT}:4000
  frontend:
    ports:
      - ${CLIENT_PORT}:5173
