services:
  nginx:
    image: jonasal/nginx-certbot:latest
    ports:
      - 80:80
      - 443:443
    environment:
      - CERBOT_NAME=${CERBOT_NAME}
      - DOMAIN=${DOMAIN}
    volumes:
      - ${PROJECT_PATH}/docker/template_start_nginx_prod.sh:/scripts/template_start.sh
      - ${PROJECT_PATH}/docker/nginx.prod.template:/etc/nginx/user_conf.d/nginx.prod.template
      - ${PROJECT_PATH}/frontend/dist:/var/www/frontend
      - ${DATA_PATH}/projects/static:/api/static
    command: ["/scripts/template_start.sh"]
